# Generated by Django 5.1.4 on 2025-02-10 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=122)),
                ('short_description', models.CharField(max_length=122)),
                ('description', models.TextField(max_length=122)),
                ('created_date', models.DateTimeField()),
                ('end_date', models.IntegerField()),
                ('type', models.IntegerField()),
                ('developers', models.CharField(max_length=122)),
            ],
        ),
    ]
