# Generated by Django 5.1.6 on 2025-02-27 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_question'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Question',
        ),
    ]
