# Generated by Django 5.1.6 on 2025-02-27 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_project_start_date_project_start_datetime_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='project',
            name='start_datetime',
        ),
        migrations.RemoveField(
            model_name='project',
            name='start_month',
        ),
        migrations.RemoveField(
            model_name='project',
            name='start_time',
        ),
        migrations.RemoveField(
            model_name='project',
            name='start_year',
        ),
        migrations.AlterField(
            model_name='project',
            name='created_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
