# Generated by Django 5.1.6 on 2025-03-03 04:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_remove_project_start_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=150)),
                ('Description', models.TextField(max_length=250)),
                ('priority', models.CharField(max_length=150)),
                ('status', models.CharField(max_length=150)),
                ('Deadline', models.DateTimeField(blank=True, null=True)),
                ('created_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('Assigned_to', models.ManyToManyField(related_name='task', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
