# Generated by Django 5.1.6 on 2025-03-03 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='task',
            name='end_date',
        ),
    ]
