# Generated by Django 5.1.6 on 2025-03-05 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_developer_team_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='developers',
            field=models.ManyToManyField(related_name='projects', to='home.developer'),
        ),
    ]
