# Generated by Django 5.1.6 on 2025-03-04 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_task_created_date_task_end_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='Assigned_to',
            new_name='assigned_to',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='Deadline',
            new_name='deadline',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='Description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='Title',
            new_name='title',
        ),
    ]
