# Generated by Django 5.1.6 on 2025-03-12 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_alter_task_description_alter_task_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='type',
            field=models.CharField(choices=[('Web', 'Web Development'), ('Software', 'Software Development'), ('Data', 'Data Science'), ('AI', 'Artificial Intelligence')], max_length=12),
        ),
    ]
